version: "0.0.0"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/guitarstoreapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=toor
  db:
    image: postgres
    environment:
      - POSTGRES_DB=guitarstoreapp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor